image: Visual Studio 2022
environment:
  global:
    MINICONDA: C:\Miniconda38-x64
  matrix:
    - PYTHON_VERSION: 3.6
    - PYTHON_VERSION: 3.7
    - PYTHON_VERSION: 3.8
    - PYTHON_VERSION: 3.9
    - PYTHON_VERSION: 3.10
install:
  - "set PATH=%MINICONDA%\\condabin;%PATH%"
  - call "%MINICONDA%\\Scripts\\activate.bat"
  - conda config --set always_yes yes
  - conda config --set channel_priority strict
  - conda config --add channels conda-forge
  - conda config --remove channels defaults
  - appveyor-retry conda install --name base mamba
  - appveyor-retry mamba create --quiet --yes --name ci
        "pip"
        "python=%PYTHON_VERSION%"
        "setuptools>=27.3"
  - conda activate ci
  - conda info --all
  - conda list
build_script:
  - python -m pip install .[test]
test_script:
  - python -m pytest
        --color yes
        --code-highlight yes
        --cov igwn_auth_utils
        --junitxml junit.xml
        --pyargs igwn_auth_utils.tests
        -ra
        --verbose
on_finish:
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\junit.xml))
